Added ui config, region, network and subnetwork api
Shreyasls/vertex_scheduler_main pull request #1
Opened 2024-11-20 10:53 UTC by risha-vijayvargiya-22

2024-11-21 10:08 UTC, harsha-accenture requested changes

2024-11-21 10:08 UTC, harsha-accenture commented on dataproc_jupyter_plugin/controllers/vertex/cloudStorageBucket.py
> +class CloudStorageBucketController(APIHandler):
Change the name to CloudStorageController and move the class to the storage.py file

2024-11-21 10:08 UTC, harsha-accenture commented on dataproc_jupyter_plugin/controllers/vertex/network.py
> +class NetworkController(APIHandler):
Move this method to a file called compute.py

2024-11-21 10:08 UTC, harsha-accenture commented on dataproc_jupyter_plugin/controllers/vertex/region.py
> +class RegionController(APIHandler):
Move to compute.py

2024-11-21 10:08 UTC, harsha-accenture commented on dataproc_jupyter_plugin/controllers/vertex/sharedNetwork.py
> +class SharedNetworkController(APIHandler):
Move to compute.py

2024-11-21 10:08 UTC, harsha-accenture commented on dataproc_jupyter_plugin/controllers/vertex/subNetwork.py
> +class SubNetworkController(APIHandler):
Move to compute.py

2024-11-21 10:08 UTC, harsha-accenture commented on dataproc_jupyter_plugin/controllers/vertex/uiConfig.py
> +class UIConfigController(APIHandler):
Move to vertex.py

2024-11-21 10:08 UTC, harsha-accenture commented on dataproc_jupyter_plugin/handlers.py
> +        "api/vertex/cloudStorageBucket": cloudStorageBucket.CloudStorageBucketController
change this to api/storage/listBuckets

2024-11-21 10:08 UTC, harsha-accenture commented on dataproc_jupyter_plugin/handlers.py
> +        "api/vertex/region": region.RegionController,
change this to api/compute/**

2024-12-04 21:27 UTC, brian-nguyen approved these changes

2024-12-18 12:51 UTC, harsha-accenture requested changes

2024-12-18 12:51 UTC, harsha-accenture commented on dataproc_jupyter_plugin/services/compute.py
> +            compute_client = compute_v1.RegionsClient(credentials=credentials)
Rename the variable to regions_client

2024-12-18 12:51 UTC, harsha-accenture commented on dataproc_jupyter_plugin/services/compute.py
> +            compute_client = compute_v1.NetworksClient(credentials=credentials)
Rename the variable to networks_client

2024-12-18 12:51 UTC, harsha-accenture commented on dataproc_jupyter_plugin/services/compute.py
> +            compute_client = compute_v1.SubnetworksClient(credentials=credentials)
Rename the variable to subnetworks_client

2024-12-18 12:51 UTC, harsha-accenture commented on dataproc_jupyter_plugin/services/compute.py
> +            compute_client = compute_v1.SubnetworksClient(credentials=credentials)
Rename the variable to subnetworks_client

2024-12-18 12:51 UTC, harsha-accenture commented on dataproc_jupyter_plugin/services/iam.py
> +            iam_admin_client = iam_admin_v1.IAMAsyncClient(credentials=credentials)
Rename the variable to iam_client

2024-12-18 12:51 UTC, harsha-accenture commented on dataproc_jupyter_plugin/controllers/storage.py
> +            async with aiohttp.ClientSession() as client_session:
If we are using client library, why do we need this session?

2024-12-18 12:51 UTC, harsha-accenture commented on dataproc_jupyter_plugin/services/storage.py
> +    def __init__(self, credentials, log, client_session):
Remove client_session if we are using client library

2024-12-18 12:51 UTC, harsha-accenture commented on dataproc_jupyter_plugin/services/storage.py
> +        self.client_session = client_session
Remove client_session if we are using client library

2024-12-19 11:01 UTC, harsha-accenture approved these changes

2024-12-19 11:01 UTC, merged