added the create new bucket functionality and updated the color codes…
Shreyasls/vertex_scheduler_main pull request #6
Opened 2024-12-24 05:53 UTC by shreyas-ls

… in the execution history page.
disabled the past and future date based on the job created and current date.

2025-01-10 10:19 UTC, harsha-accenture requested changes

2025-01-10 10:19 UTC, harsha-accenture commented on src/Services/Storage.tsx
> +                toast.success(
Should this not be error toast?

2025-01-10 10:19 UTC, harsha-accenture commented on src/Services/Storage.tsx
> +            toast.success(
Should this not be error toast?

2025-01-10 10:19 UTC, harsha-accenture commented on src/scheduler/VertexScheduler/CreateVertexScheduler.tsx
> +                                // open={true}
Remove the commented line.

2025-01-10 10:19 UTC, harsha-accenture commented on src/scheduler/VertexScheduler/ListVertexScheduler.tsx
>    console.debug(isPreviewEnabled)
Why is this required?

2025-01-10 10:19 UTC, harsha-accenture commented on src/scheduler/VertexScheduler/ListVertexScheduler.tsx
>    console.debug(nextPageFlag);
Why is this required?

2025-01-10 10:23 UTC, harsha-accenture requested changes

2025-01-10 10:23 UTC, harsha-accenture commented on src/scheduler/VertexScheduler/VertexExecutionHistory.tsx
> +            backgroundColor = '#3B78E7';
Why is this logic not reused from composer implementation?

2025-01-10 10:23 UTC, harsha-accenture commented on src/scheduler/VertexScheduler/VertexJobTaskLogs.tsx
> +        console.debug(index, iconIndex)
Why is this required?

2025-01-10 11:57 UTC, shreyas-ls commented on src/scheduler/VertexScheduler/VertexJobTaskLogs.tsx
> +        console.debug(index, iconIndex)
to show the logs on the execution history. when the accordion is exapanded.

2025-01-10 11:58 UTC, shreyas-ls commented on src/scheduler/VertexScheduler/VertexExecutionHistory.tsx
> +            backgroundColor = '#3B78E7';
In composer the color code was not implemented correctly, I have fixed it in the vertex

2025-01-10 12:00 UTC, shreyas-ls commented on src/scheduler/VertexScheduler/ListVertexScheduler.tsx
>    console.debug(isPreviewEnabled)
This piece of code is implementing by Vysakh.

2025-01-16 11:45 UTC, harsha-accenture approved these changes

2025-01-17 03:51 UTC, merged